import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nexj.js Rainbowkit Starter Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ marginBottom: "4rem" }}>
          Next.js <a href="https://www.rainbowkit.com/">RainbowKit</a>
          {" "} Dapp Starter
        </h1>

        <p className={styles.description}>
          Start by connecting your wallet
        </p>
        <ConnectButton />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
